# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbd398d23d93484d851690940fa915a92b43a5488c46e20704dbb08082eec4c9f090c008c18cd4a289911ac91aaa76c3be8fea6042972b2857713c8e07896a0d

test:
  secret_key_base: bf1cb2aee954085a26d9fbf5dfcf969ea269ea0664d0a791380a93097be572d05b31687e1a862bba403787d999c63e020d05006f9c3494f4eab7bbc04410f55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
